### ISSUE TITLE
Don't download packages unless an upgrade is required

### ISSUE THREAD

**Issue by ryancragun** [chef-cookbooks/chef-ingredient#102]
Currently chef-ingredient will download packages regardless of whether or not they're up to date.

```shell
    * chef_gem[mixlib-install] action install (up to date)
    - Download chef-server package from https://packages.chef.io/stable/el/7/chef-server-core-12.5.0-1.el7.x86_64.rpm
    * ruby_block[stop chef run] action nothing (skipped due to action :nothing)
    * remote_file[/var/opt/chef-marketplace/embedded/cookbooks/cache/chef-server-core-12.5.0-1.el7.x86_64.rpm] action create
      - create new file /var/opt/chef-marketplace/embedded/cookbooks/cache/chef-server-core-12.5.0-1.el7.x86_64.rpm
      - update content in file /var/opt/chef-marketplace/embedded/cookbooks/cache/chef-server-core-12.5.0-1.el7.x86_64.rpm from none to 67c17c
      (file sizes exceed 10000000 bytes, diff output suppressed)
      - change mode from '' to '0644'
    * yum_package[chef-server] action upgrade (up to date)

```

It would be nice to validate the current version and only download the package if it's going to update it.

**Comment by schisamo** [comment]
@ryancragun The `checksum` should stop this from happening on subsequent CCRs right? What was the `version` you specified in the example above?

**Comment by ryancragun** [comment]
@schisamo I was just using the `:upgrade` action so it always stays up to date.  I didn't specify a version or checksum.  You're correct that it'll only download the file once and leave it in the cache.

**Comment by patrick-wright** [comment]
I'm a bit confused by this log because the file updated from `none`
```
      - update content in file /var/opt/chef-marketplace/embedded/cookbooks/cache/chef-server-core-12.5.0-1.el7.x86_64.rpm from none to 67c17c
```

**Comment by schisamo** [comment]
@ryancragun Yeah not providing a version is the same as providing `:latest`:
https://github.com/chef-cookbooks/chef-ingredient/blob/master/libraries/chef_ingredient_resource.rb#L29

Basically if the whatever `:latest` resolves to hasn't changed the package should not re-downloaded as we provide a `checksum

**Comment by ryancragun** [comment]
@patrick-wright The machine already had the latest version of the chef-server installed before `chef-ingredient` ran the package wasn't in the client cache, hence updated from none.  When the client ran it did download the file even though it wasn't necessary because it was already on the latest version.  My request is that we verify the package version installed with the candidate for the download and only download the file in the event that we need to change versions.  It'd also be really handy to have an auto purge feature to remove the file from the cache after the installation, otherwise we'll build quite an inventory of old packages over time.  With the old method yum/apt would handle this for us but we lose that with the new implementation.

**Comment by haidangwa** [comment]
I've noticed the downloads, as well, and I have specified `version` for all of the server packages, including chef-server, push-jobs-server, manage, and reporting. All use the default action (not explicitly specified in my recipe).

**Comment by mivok** [comment]
I just submitted a pull request (#114) that should prevent the 'Download chef-server package from ...' message from coming up every time. That may alleviate some confusion here where a change is shown in the output even though the remote_file resource is unchanged when a new version hasn't been released. This also allows you to use notifies in order to perform actions only on upgrade.

**Comment by haidangwa** [comment]
A side affect of the caching is that it also leaves the RPM on the system. On many of our servers, this arbitrarily takes up value space in our filesystems that have limited cache space allocated to them. Case in point, my cookbook uses chef_ingredient to manage chef-server-core installations and I found I was out of space when it tried to upgrade from 12.7.0 to 12.8.0. The rpm file for 12.7.0 was taking up space where if it was deleted before the upgrade, then my chef run wouldn't fail due to a lack of disk space.

Maybe this is a separate issue?

**Comment by wrightp** [comment]
Merged PR fixing the converge_by confusion. As for left over files we could create a separate ticket if this becomes a future issue to have chef-ingredient clean up after itself. Closing for now.
