### ISSUE TITLE
chef-ingredient assumes connection to the interwebs

### ISSUE THREAD

**Issue by thenoid** [chef-cookbooks/chef-ingredient#62]
Chef-ingredient assumes that the host it is running on is connected to the internet and configures/depends on the yum-chef/apt-chef.

https://github.com/chef-cookbooks/chef-ingredient/blob/master/libraries/rhel_handler.rb#L57
https://github.com/chef-cookbooks/chef-ingredient/blob/master/libraries/rhel_handler.rb#L64

Not all installs have direct access to the interwebs, even if they do, should this cookbook really assume that people want to pull directly from there?  They could have the packages mirrored internally using satellite/katello/spacewalk/artifactory, etc. and do so for good reason audit/compliance/blah/blah

While it is nice having the cookbook that works soup-to-nuts, perhaps provide the capability to say "i'll provide my own toys" and install the package w/out all the assumptions.

**Comment by thenoid** [comment]
Submitted pull request #64

**Comment by jtimberman** [comment]
You can specify a `package_source` when using the `chef_ingredient`. An example of this is in the `test::local` [recipe](https://github.com/chef-cookbooks/chef-ingredient/blob/master/test/fixtures/cookbooks/test/recipes/local.rb). 

You can also override the `yum-chef` [attributes](https://github.com/chef-cookbooks/yum-chef/blob/master/attributes/default.rb) to change where the yum repository is.

**Comment by chilicheech** [comment]
hey, @jtimberman, we had some good discussion about this in the 2 PRs referenced above.

`package_source` allows you to specify a local file to install and the installation is performed with RPM instead of YUM. It doesn't let you specify a yum repo.

Also, yum-chef does allow you to change attributes for the `default` recipe, not for `current` or `stable`, which is what `chef_ingredient` uses. As you can see, the https://github.com/chef-cookbooks/yum-chef/blob/master/recipes/stable.rb recipe doesn't allow you to customize the yum repo.

As you can see here: https://github.com/chef-cookbooks/chef-ingredient/blob/master/libraries/rhel_handler.rb#L57 and here: https://github.com/chef-cookbooks/chef-ingredient/blob/master/libraries/chef_ingredient_resource.rb#L30 only the `current` and `stable` recipes are used by `chef_ingredient`. Therefore, you actually "can't" override the `yum-chef` attributes to change where the yum repo is.

Please re-open this issue. If I'm failing to see what you're trying to say, please elaborate further.

Cheers,

**Comment by afiune** [comment]
+1 On this issue. I am re-opening and taking ownership since it makes total sense for enterprises that does not have access to the internet.

**Comment by sersut** [comment]
Thanks @afiune for checking this out. We have a proposal here:

https://github.com/chef-cookbooks/chef-ingredient/pull/65#issuecomment-159683383

What do you think about that?

**Comment by afiune** [comment]
That is terrific! Exactly what I have in mind!! :smile:

Is there anybody working in this or should I go ahead and code it?

On Friday, December 4, 2015, Serdar Sutay <notifications@github.com> wrote:

> Thanks @afiune <https://github.com/afiune> for checking this out. We have
> a proposal here:
>
> #65 (comment)
> <https://github.com/chef-cookbooks/chef-ingredient/pull/65#issuecomment-159683383>
>
> What do you think about that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chef-cookbooks/chef-ingredient/issues/62#issuecomment-162029526>
> .
>


-- 

*Salim Afiune* — Solutions Engineer

917.716.0448 – afiune@chef.io – *my: *Linkedin
<http://www.linkedin.com/in/afiune>  Twitter <http://www.twitter.com/afiune>

CHEF

      CHEF.IO <http://www.chef.io/>

TM

*chef.io <http://www.chef.io/>*   Blog <http://www.chef.io/blog/>   Facebook
<https://www.facebook.com/getchefdotcom>   Twitter
<https://twitter.com/chef>   Youtube <https://www.youtube.com/getchef>
