### ISSUE TITLE
Fetch of mixlib-install from Rubygems is unfriendly to heavily firewalled or isolated environments

### ISSUE THREAD

**Issue by irvingpop** [chef-cookbooks/chef-ingredient#87]
In [libraries/helpers.rb](https://github.com/chef-cookbooks/chef-ingredient/blob/master/libraries/helpers.rb) there are two methods (`ensure_mixlib_install_gem_installed!` and `install_gem_from_rubygems`) that assume a user would want to grab the `mixlib-install` gem from Rubygems.org.  

We need to provide an alternative method for Enterprise customers who's firewall access is highly restrictive or who attempt to use our services in Internet-isolated environments. 

Some ideas:
* Make the gem source configurable in `install_gem_from_rubygems` (this forces customers to run a Rubygems mirror-like thing)
* Enable `chef-ingredient` to grab a tarball of the `mixlib-install` source from somewhere, build and install locally

**Comment by patrick-wright** [comment]
@irvingpop There is an open PR to support installing mixlib-install from source.  https://github.com/chef-cookbooks/chef-ingredient/pull/86/files Should be merged this week.  Since this may be something we need to do more of in the future I started a new cookbook to support installing gems from source as a Chef resource. https://github.com/patrick-wright/git-gem/

**Comment by patrick-wright** [comment]
support to install from source has been merged into master
